# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [2]:
import pandas as pd
from IPython.display import display

In [3]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"

df = pd.read_csv(url)

print(df.shape)
display(df.head())

(10910, 26)

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [4]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_")
)

display(df.head())

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [5]:
df.info()

display(df.describe(include="all"))

<class 'pandas.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  str
 2   state                          10279 non-null  str
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10279 non-null  str
 5   coverage                       10910 non-null  str
 6   education                      10910 non-null  str
 7   effective_to_date              10910 non-null  str
 8   employmentstatus               10910 non-null  str
 9   gender                         10910 non-null  str
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  str
 12  marital_status                 10910 non-null  str
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10277 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10277 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  str
 19  policy                         10910 non-null  str
 20  renew_offer_type               10910 non-null  str
 21  sales_channel                  10910 non-null  str
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10288 non-null  str
 24  vehicle_size                   10288 non-null  str
 25  vehicle_type                   5428 non-null   str
dtypes: float64(4), int64(5), str(17)
memory usage: 2.2 MB

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
count,10910.000000,10910,10279,10910.000000,10279,10910,10910,10910,10910,10910,...,10277.000000,10910.000000,10910,10910,10910,10910,10910.000000,10288,10288,5428
unique,NaN,9134,5,NaN,2,3,5,59,5,2,...,NaN,NaN,3,9,4,4,NaN,6,3,1
top,NaN,ID89933,California,NaN,No,Basic,Bachelor,1/27/11,Employed,F,...,NaN,NaN,Personal Auto,Personal L3,Offer1,Agent,NaN,Four-Door Car,Medsize,A
freq,NaN,7,3552,NaN,8813,6660,3272,239,6789,5573,...,NaN,NaN,8128,4118,4483,4121,NaN,5212,7251,5428
mean,5454.500000,NaN,NaN,8018.241094,NaN,NaN,NaN,NaN,NaN,NaN,...,0.384256,2.979193,NaN,NaN,NaN,NaN,434.888330,NaN,NaN,NaN
std,3149.590053,NaN,NaN,6885.081434,NaN,NaN,NaN,NaN,NaN,NaN,...,0.912457,2.399359,NaN,NaN,NaN,NaN,292.180556,NaN,NaN,NaN
min,0.000000,NaN,NaN,1898.007675,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,1.000000,NaN,NaN,NaN,NaN,0.099007,NaN,NaN,NaN
25%,2727.250000,NaN,NaN,4014.453113,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,1.000000,NaN,NaN,NaN,NaN,271.082527,NaN,NaN,NaN
50%,5454.500000,NaN,NaN,5771.147235,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,2.000000,NaN,NaN,NaN,NaN,382.564630,NaN,NaN,NaN
75%,8181.750000,NaN,NaN,8992.779137,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,4.000000,NaN,NaN,NaN,NaN,547.200000,NaN,NaN,NaN
max,10909.000000,NaN,NaN,83325.381190,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,9.000000,NaN,NaN,NaN,NaN,2893.239678,NaN,NaN,NaN

In [6]:
low_claim_yes = df[
    (df["total_claim_amount"] < 1000) &
    (df["response"] == "Yes")
]

print(low_claim_yes.shape)

display(low_claim_yes.head())

(1399, 26)

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN

In [7]:
premium_clv = (
    df[df["response"] == "Yes"]
    .groupby(["policy_type", "gender"])
    .agg({
        "monthly_premium_auto": "mean",
        "customer_lifetime_value": "mean"
    })
    .round(2)
)

display(premium_clv)

                       monthly_premium_auto  customer_lifetime_value
policy_type    gender
Corporate Auto F                      94.30                  7712.63
               M                      92.19                  7944.47
Personal Auto  F                      99.00                  8339.79
               M                      91.09                  7448.38
Special Auto   F                      92.31                  7691.58
               M                      86.34                  8247.09

In [8]:
claim_analysis = (
    df[df["response"] == "Yes"]
    .groupby(["policy_type", "gender"])
    .agg({
        "monthly_premium_auto": "mean",
        "customer_lifetime_value": "mean",
        "total_claim_amount": "mean"
    })
    .round(2)
)

display(claim_analysis)

                       monthly_premium_auto  customer_lifetime_value  \
policy_type    gender
Corporate Auto F                      94.30                  7712.63
               M                      92.19                  7944.47
Personal Auto  F                      99.00                  8339.79
               M                      91.09                  7448.38
Special Auto   F                      92.31                  7691.58
               M                      86.34                  8247.09

                       total_claim_amount
policy_type    gender
Corporate Auto F                   433.74
               M                   408.58
Personal Auto  F                   452.97
               M                   457.01
Special Auto   F                   453.28
               M                   429.53

In [9]:
state_counts = (
    df["state"]
    .value_counts()
    .rename_axis("state")
    .reset_index(name="number_of_customers")
)

display(state_counts)

        state  number_of_customers
0  California                 3552
1      Oregon                 2909
2     Arizona                 1937
3      Nevada                  993
4  Washington                  888

In [10]:
large_states = state_counts[
    state_counts["number_of_customers"] > 500
]

display(large_states)

        state  number_of_customers
0  California                 3552
1      Oregon                 2909
2     Arizona                 1937
3      Nevada                  993
4  Washington                  888

In [11]:
clv_summary = (
    df.groupby(["education", "gender"])["customer_lifetime_value"]
    .agg(["max", "min", "median"])
    .round(2)
)

display(clv_summary)

                                  max      min   median
education            gender
Bachelor             F       73225.96  1904.00  5640.51
                     M       67907.27  1898.01  5548.03
College              F       61850.19  1898.68  5623.61
                     M       61134.68  1918.12  6005.85
Doctor               F       44856.11  2395.57  5332.46
                     M       32677.34  2267.60  5577.67
High School or Below F       55277.45  2144.92  6039.55
                     M       83325.38  1940.98  6286.73
Master               F       51016.07  2417.78  5729.86
                     M       50568.26  2272.31  5579.10

In [12]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"

df = pd.read_csv(url)

df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_")
)

display(df.head())

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [15]:
print(df.columns.tolist())

['unnamed:_0', 'customer', 'state', 'customer_lifetime_value', 'response', 'coverage', 'education', 'effective_to_date', 'employmentstatus', 'gender', 'income', 'location_code', 'marital_status', 'monthly_premium_auto', 'months_since_last_claim', 'months_since_policy_inception', 'number_of_open_complaints', 'number_of_policies', 'policy_type', 'policy', 'renew_offer_type', 'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size', 'vehicle_type']

In [16]:
df["effective_to_date"] = pd.to_datetime(df["effective_to_date"])

/var/folders/3_/6lgqyskd5v55bylpxy1jbmzr0000gn/T/ipykernel_71343/1646485608.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["effective_to_date"] = pd.to_datetime(df["effective_to_date"])

In [17]:
df["month"] = df["effective_to_date"].dt.month_name()

In [18]:
df["month"] = df["effective_to_date"].dt.month

In [20]:
display(df[["effective_to_date", "month"]].head())

  effective_to_date  month
0        2011-02-18      2
1        2011-01-18      1
2        2011-02-10      2
3        2011-01-11      1
4        2011-01-17      1

In [22]:
state_month = (
    df.groupby(["state", "month"])
      .size()
      .reset_index(name="policies_sold")
)

display(state_month)

        state  month  policies_sold
0     Arizona      1           1008
1     Arizona      2            929
2  California      1           1918
3  California      2           1634
4      Nevada      1            551
5      Nevada      2            442
6      Oregon      1           1565
7      Oregon      2           1344
8  Washington      1            463
9  Washington      2            425

In [23]:
top_states = (
    df["state"]
    .value_counts()
    .head(3)
)

display(top_states)

state
California    3552
Oregon        2909
Arizona       1937
Name: count, dtype: int64

In [24]:
top3_table = (
    state_month[state_month["state"].isin(top_states.index)]
    .pivot(index="state",
           columns="month",
           values="policies_sold")
    .fillna(0)
    .astype(int)
)

display(top3_table)

month          1     2
state
Arizona     1008   929
California  1918  1634
Oregon      1565  1344

In [25]:
top3_states = df["state"].value_counts().head(3).index

top3_table = (
    df[df["state"].isin(top3_states)]
      .groupby(["state", "month"])
      .size()
      .unstack(fill_value=0)
)

display(top3_table)

month          1     2
state
Arizona     1008   929
California  1918  1634
Oregon      1565  1344

In [26]:
display(df.columns)

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='str')

In [27]:
marketing = df.melt(
    id_vars="response",
    value_vars=["sales_channel"],
    var_name="marketing_channel",
    value_name="channel"
)

display(marketing.head())

  response marketing_channel      channel
0       No     sales_channel        Agent
1       No     sales_channel  Call Center
2       No     sales_channel  Call Center
3      Yes     sales_channel       Branch
4       No     sales_channel       Branch

In [28]:
response_rate = (
    marketing.groupby("channel")["response"]
             .apply(lambda x: (x == "Yes").mean() * 100)
             .reset_index(name="response_rate")
             .sort_values("response_rate", ascending=False)
)

display(response_rate)

       channel  response_rate
0        Agent      18.005339
3          Web      10.885609
1       Branch      10.787558
2  Call Center      10.322279

In [29]:
response_rate = (
    df.groupby("sales_channel")["response"]
      .apply(lambda x: (x == "Yes").mean() * 100)
      .reset_index(name="response_rate")
      .sort_values("response_rate", ascending=False)
)

display(response_rate)

  sales_channel  response_rate
0         Agent      18.005339
3           Web      10.885609
1        Branch      10.787558
2   Call Center      10.322279